from src.fonts import FontBase

class Font(FontBase):

    def __init__(self, char='X') -> None:
        super().__init__()
        self.char = char


    def get(self, char):
        if char in self._digits:
            return [line.replace('X', self.char) for line in self._digits[char]]
        else:
            return char


    _digits = {
        ":" : [
            "      ",
            "      ",
            "      ",
            "  XX  ",
            "  XX  ",
            "      ",
            "      ",
            "      ",
            "      ",
            "      ",
            "  XX  ",
            "  XX  ",
            "      ",
            "      ",
        ],
        "/" : [
            "              X ",
            "             X  ",
            "            X   ",
            "           X    ",
            "          X     ",
            "         X      ",
            "        X       ",
            "       X        ",
            "      X         ",
            "     X          ",
            "    X           ",
            "   X            ",
            "  X             ",
            " X              ",
        ],
        "0" : [
            "     XXXXXX     ",
            "   XXXXXXXXXX   ",
            "  XXXX    XXXX  ",
            " XXX        XXX ",
            " XXX        XXX ",
            " XXX        XXX ",
            " XXX        XXX ",
            " XXX        XXX ",
            " XXX        XXX ",
            " XXX        XXX ",
            " XXXX      XXXX ",
            "  XXXX    XXXX  ",
            "   XXXXXXXXXX   ",
            "     XXXXXX     ",
        ],
        "1" : [
            "       XXXXX    ",
            "     XXXXXXX    ",
            "     XXX XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
            "         XXX    ",
        ],
        "2" : [
            "   XXXXXXXX     ",
            "  XXXXXXXXXXX   ",
            "  XX      XXXX  ",
            "           XXX  ",
            "           XXX  ",
            "          XXXX  ",
            "          XXX   ",
            "        XXXX    ",
            "       XXXX     ",
            "     XXXXX      ",
            "    XXXX        ",
            "  XXXX          ",
            " XXXXXXXXXXXXX  ",
            " XXXXXXXXXXXXX  ",
        ],
        "3" : [
            "  XXXXXXXXX     ",
            "  XXXXXXXXXXX   ",
            "  XX      XXX   ",
            "          XXXX  ",
            "          XXX   ",
            "    XXXXXXXX    ",
            "    XXXXXXX     ",
            "       XXXXXX   ",
            "          XXXX  ",
            "           XXX  ",
            "           XXX  ",
            "  XX      XXXX  ",
            " XXXXXXXXXXXX   ",
            "  XXXXXXXXX     ",
        ],
        "4" : [
            "         XXXX   ",
            "        XXXXX   ",
            "       XXXXXX   ",
            "      XXX XXX   ",
            "     XXX  XXX   ",
            "    XXX   XXX   ",
            "   XXX    XXX   ",
            "  XXX     XXX   ",
            " XXXXXXXXXXXXXX ",
            "XXXXXXXXXXXXXXX ",
            "          XXX   ",
            "          XXX   ",
            "          XXX   ",
            "          XXX   ",
        ],
        "5" : [
            "    XXXXXXXXXX  ",
            "   XXXXXXXXXXX  ",
            "  XXX           ",
            "  XXX           ",
            "  XX            ",
            "  XXXXXXXXX     ",
            "  XXXXXXXXXXX   ",
            "          XXXX  ",
            "           XXX  ",
            "           XXX  ",
            "           XXX  ",
            "  X      XXXX   ",
            " XXXXXXXXXXX    ",
            "  XXXXXXXX      ",
        ],
        "6" : [
            "      XXXXXXX   ",
            "    XXXXXXXXX   ",
            "   XXXXX        ",
            "  XXX           ",
            " XXX            ",
            " XXXXXXXXXXX    ",
            "XXXXXXXXXXXXXX  ",
            "XXXX       XXX  ",
            "XXX        XXXX ",
            "XXX        XXXX ",
            " XXX       XXX  ",
            " XXXX     XXXX  ",
            "  XXXXXXXXXXX   ",
            "    XXXXXXX     ",
        ],
        "7" : [
            " XXXXXXXXXXXXX  ",
            " XXXXXXXXXXXXX  ",
            "          XXXX  ",
            "          XXX   ",
            "         XXX    ",
            "        XXX     ",
            "       XXXX     ",
            "      XXXX      ",
            "     XXXX       ",
            "     XXX        ",
            "    XXXX        ",
            "   XXXX         ",
            "  XXXX          ",
            "  XXX           ",
        ],
        "8" : [
            "    XXXXXXX     ",
            "  XXXXXXXXXXX   ",
            " XXXX     XXXX  ",
            " XXX       XXX  ",
            " XXXX     XXXX  ",
            " XXXXX  XXXXX   ",
            "    XXXXXXX     ",
            "  XXXXXXXXXXX   ",
            " XXXX     XXXX  ",
            "XXXX       XXXX ",
            "XXXX       XXXX ",
            " XXXX     XXXX  ",
            "  XXXXXXXXXXX   ",
            "    XXXXXXX     ",
        ],
        "9" : [
            "      XXXXXXX   ",
            "   XXXXXXXXXXX  ",
            "  XXXX     XXXX ",
            "  XXX       XXX ",
            " XXXX       XXX ",
            " XXXX       XXX ",
            "  XXXX     XXXX ",
            "   XXXXXXXXXXXX ",
            "    XXXXXXX XXX ",
            "           XXXX ",
            "          XXXX  ",
            "        XXXXX   ",
            "   XXXXXXXX     ",
            "   XXXXXX       ",
        ],
    }
